name: Test, Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Setup and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: test
        run: npm test
      - name: build
        run: npm run build-prod
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Repo
       uses: actions/checkout@master
     - name: Clear current dependencies
       run: rm -fr node_modules
     - name: Install Dependencies
       run: npm install
     - name: npm rebuild
       run: npm rebuild
     - name: Deploy to Firebase
       uses: w9jds/firebase-action@master
       with:
          args: deploy
       env:
          FIREBASE_TOKEN: 1//0gXSVoXeqmlPCCgYIARAAGBASNgF-L9IrkYwwix2C32MXv5E6SIFju1jmMZVQG7JbSGtpzRlTUGuNOSFaDl6WlrWXvB9mvKbj1g
